#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ColegioDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEstudiante(Estudiante instance);
    partial void UpdateEstudiante(Estudiante instance);
    partial void DeleteEstudiante(Estudiante instance);
    partial void InsertMateria(Materia instance);
    partial void UpdateMateria(Materia instance);
    partial void DeleteMateria(Materia instance);
    partial void InsertProfesor(Profesor instance);
    partial void UpdateProfesor(Profesor instance);
    partial void DeleteProfesor(Profesor instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.ColegioDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Estudiante> Estudiante
		{
			get
			{
				return this.GetTable<Estudiante>();
			}
		}
		
		public System.Data.Linq.Table<Materia> Materia
		{
			get
			{
				return this.GetTable<Materia>();
			}
		}
		
		public System.Data.Linq.Table<Profesor> Profesor
		{
			get
			{
				return this.GetTable<Profesor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estudiante")]
	public partial class Estudiante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EstudianteId;
		
		private string _Alu_Nombre;
		
		private System.Nullable<System.DateTime> _Alu_FechaNacimiento;
		
		private string _Alu_SignoZodiacal;
		
		private string _Alu_Foto;
		
		private System.Nullable<int> _MateriaId;
		
		private EntityRef<Materia> _Materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEstudianteIdChanging(int value);
    partial void OnEstudianteIdChanged();
    partial void OnAlu_NombreChanging(string value);
    partial void OnAlu_NombreChanged();
    partial void OnAlu_FechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnAlu_FechaNacimientoChanged();
    partial void OnAlu_SignoZodiacalChanging(string value);
    partial void OnAlu_SignoZodiacalChanged();
    partial void OnAlu_FotoChanging(string value);
    partial void OnAlu_FotoChanged();
    partial void OnMateriaIdChanging(System.Nullable<int> value);
    partial void OnMateriaIdChanged();
    #endregion
		
		public Estudiante()
		{
			this._Materia = default(EntityRef<Materia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstudianteId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EstudianteId
		{
			get
			{
				return this._EstudianteId;
			}
			set
			{
				if ((this._EstudianteId != value))
				{
					this.OnEstudianteIdChanging(value);
					this.SendPropertyChanging();
					this._EstudianteId = value;
					this.SendPropertyChanged("EstudianteId");
					this.OnEstudianteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alu_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Alu_Nombre
		{
			get
			{
				return this._Alu_Nombre;
			}
			set
			{
				if ((this._Alu_Nombre != value))
				{
					this.OnAlu_NombreChanging(value);
					this.SendPropertyChanging();
					this._Alu_Nombre = value;
					this.SendPropertyChanged("Alu_Nombre");
					this.OnAlu_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alu_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> Alu_FechaNacimiento
		{
			get
			{
				return this._Alu_FechaNacimiento;
			}
			set
			{
				if ((this._Alu_FechaNacimiento != value))
				{
					this.OnAlu_FechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._Alu_FechaNacimiento = value;
					this.SendPropertyChanged("Alu_FechaNacimiento");
					this.OnAlu_FechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alu_SignoZodiacal", DbType="VarChar(50)")]
		public string Alu_SignoZodiacal
		{
			get
			{
				return this._Alu_SignoZodiacal;
			}
			set
			{
				if ((this._Alu_SignoZodiacal != value))
				{
					this.OnAlu_SignoZodiacalChanging(value);
					this.SendPropertyChanging();
					this._Alu_SignoZodiacal = value;
					this.SendPropertyChanged("Alu_SignoZodiacal");
					this.OnAlu_SignoZodiacalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alu_Foto", DbType="VarChar(MAX)")]
		public string Alu_Foto
		{
			get
			{
				return this._Alu_Foto;
			}
			set
			{
				if ((this._Alu_Foto != value))
				{
					this.OnAlu_FotoChanging(value);
					this.SendPropertyChanging();
					this._Alu_Foto = value;
					this.SendPropertyChanged("Alu_Foto");
					this.OnAlu_FotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaId", DbType="Int")]
		public System.Nullable<int> MateriaId
		{
			get
			{
				return this._MateriaId;
			}
			set
			{
				if ((this._MateriaId != value))
				{
					if (this._Materia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMateriaIdChanging(value);
					this.SendPropertyChanging();
					this._MateriaId = value;
					this.SendPropertyChanged("MateriaId");
					this.OnMateriaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Estudiante", Storage="_Materia", ThisKey="MateriaId", OtherKey="MateriaId", IsForeignKey=true)]
		public Materia Materia
		{
			get
			{
				return this._Materia.Entity;
			}
			set
			{
				Materia previousValue = this._Materia.Entity;
				if (((previousValue != value) 
							|| (this._Materia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Materia.Entity = null;
						previousValue.Estudiante.Remove(this);
					}
					this._Materia.Entity = value;
					if ((value != null))
					{
						value.Estudiante.Add(this);
						this._MateriaId = value.MateriaId;
					}
					else
					{
						this._MateriaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Materia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materia")]
	public partial class Materia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MateriaId;
		
		private string _Mat_Nombre;
		
		private string _Mat_Descripcion;
		
		private System.Nullable<int> _ProfesorId;
		
		private EntitySet<Estudiante> _Estudiante;
		
		private EntityRef<Profesor> _Profesor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMateriaIdChanging(int value);
    partial void OnMateriaIdChanged();
    partial void OnMat_NombreChanging(string value);
    partial void OnMat_NombreChanged();
    partial void OnMat_DescripcionChanging(string value);
    partial void OnMat_DescripcionChanged();
    partial void OnProfesorIdChanging(System.Nullable<int> value);
    partial void OnProfesorIdChanged();
    #endregion
		
		public Materia()
		{
			this._Estudiante = new EntitySet<Estudiante>(new Action<Estudiante>(this.attach_Estudiante), new Action<Estudiante>(this.detach_Estudiante));
			this._Profesor = default(EntityRef<Profesor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateriaId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MateriaId
		{
			get
			{
				return this._MateriaId;
			}
			set
			{
				if ((this._MateriaId != value))
				{
					this.OnMateriaIdChanging(value);
					this.SendPropertyChanging();
					this._MateriaId = value;
					this.SendPropertyChanged("MateriaId");
					this.OnMateriaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Mat_Nombre
		{
			get
			{
				return this._Mat_Nombre;
			}
			set
			{
				if ((this._Mat_Nombre != value))
				{
					this.OnMat_NombreChanging(value);
					this.SendPropertyChanging();
					this._Mat_Nombre = value;
					this.SendPropertyChanged("Mat_Nombre");
					this.OnMat_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Mat_Descripcion
		{
			get
			{
				return this._Mat_Descripcion;
			}
			set
			{
				if ((this._Mat_Descripcion != value))
				{
					this.OnMat_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._Mat_Descripcion = value;
					this.SendPropertyChanged("Mat_Descripcion");
					this.OnMat_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorId", DbType="Int")]
		public System.Nullable<int> ProfesorId
		{
			get
			{
				return this._ProfesorId;
			}
			set
			{
				if ((this._ProfesorId != value))
				{
					if (this._Profesor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfesorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfesorId = value;
					this.SendPropertyChanged("ProfesorId");
					this.OnProfesorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Materia_Estudiante", Storage="_Estudiante", ThisKey="MateriaId", OtherKey="MateriaId")]
		public EntitySet<Estudiante> Estudiante
		{
			get
			{
				return this._Estudiante;
			}
			set
			{
				this._Estudiante.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Materia", Storage="_Profesor", ThisKey="ProfesorId", OtherKey="ProfesorId", IsForeignKey=true)]
		public Profesor Profesor
		{
			get
			{
				return this._Profesor.Entity;
			}
			set
			{
				Profesor previousValue = this._Profesor.Entity;
				if (((previousValue != value) 
							|| (this._Profesor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesor.Entity = null;
						previousValue.Materia.Remove(this);
					}
					this._Profesor.Entity = value;
					if ((value != null))
					{
						value.Materia.Add(this);
						this._ProfesorId = value.ProfesorId;
					}
					else
					{
						this._ProfesorId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Profesor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estudiante(Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Materia = this;
		}
		
		private void detach_Estudiante(Estudiante entity)
		{
			this.SendPropertyChanging();
			entity.Materia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesor")]
	public partial class Profesor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProfesorId;
		
		private string _Pro_Nombre;
		
		private System.Nullable<System.DateTime> _Pro_FechaNacimiento;
		
		private string _Pro_SignoZodiacal;
		
		private string _Pro_Especialidad;
		
		private string _Pro_FotoPath;
		
		private EntitySet<Materia> _Materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfesorIdChanging(int value);
    partial void OnProfesorIdChanged();
    partial void OnPro_NombreChanging(string value);
    partial void OnPro_NombreChanged();
    partial void OnPro_FechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnPro_FechaNacimientoChanged();
    partial void OnPro_SignoZodiacalChanging(string value);
    partial void OnPro_SignoZodiacalChanged();
    partial void OnPro_EspecialidadChanging(string value);
    partial void OnPro_EspecialidadChanged();
    partial void OnPro_FotoPathChanging(string value);
    partial void OnPro_FotoPathChanged();
    #endregion
		
		public Profesor()
		{
			this._Materia = new EntitySet<Materia>(new Action<Materia>(this.attach_Materia), new Action<Materia>(this.detach_Materia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProfesorId
		{
			get
			{
				return this._ProfesorId;
			}
			set
			{
				if ((this._ProfesorId != value))
				{
					this.OnProfesorIdChanging(value);
					this.SendPropertyChanging();
					this._ProfesorId = value;
					this.SendPropertyChanged("ProfesorId");
					this.OnProfesorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Pro_Nombre
		{
			get
			{
				return this._Pro_Nombre;
			}
			set
			{
				if ((this._Pro_Nombre != value))
				{
					this.OnPro_NombreChanging(value);
					this.SendPropertyChanging();
					this._Pro_Nombre = value;
					this.SendPropertyChanged("Pro_Nombre");
					this.OnPro_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> Pro_FechaNacimiento
		{
			get
			{
				return this._Pro_FechaNacimiento;
			}
			set
			{
				if ((this._Pro_FechaNacimiento != value))
				{
					this.OnPro_FechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._Pro_FechaNacimiento = value;
					this.SendPropertyChanged("Pro_FechaNacimiento");
					this.OnPro_FechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_SignoZodiacal", DbType="VarChar(50)")]
		public string Pro_SignoZodiacal
		{
			get
			{
				return this._Pro_SignoZodiacal;
			}
			set
			{
				if ((this._Pro_SignoZodiacal != value))
				{
					this.OnPro_SignoZodiacalChanging(value);
					this.SendPropertyChanging();
					this._Pro_SignoZodiacal = value;
					this.SendPropertyChanged("Pro_SignoZodiacal");
					this.OnPro_SignoZodiacalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Especialidad", DbType="VarChar(100)")]
		public string Pro_Especialidad
		{
			get
			{
				return this._Pro_Especialidad;
			}
			set
			{
				if ((this._Pro_Especialidad != value))
				{
					this.OnPro_EspecialidadChanging(value);
					this.SendPropertyChanging();
					this._Pro_Especialidad = value;
					this.SendPropertyChanged("Pro_Especialidad");
					this.OnPro_EspecialidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_FotoPath", DbType="VarChar(255)")]
		public string Pro_FotoPath
		{
			get
			{
				return this._Pro_FotoPath;
			}
			set
			{
				if ((this._Pro_FotoPath != value))
				{
					this.OnPro_FotoPathChanging(value);
					this.SendPropertyChanging();
					this._Pro_FotoPath = value;
					this.SendPropertyChanged("Pro_FotoPath");
					this.OnPro_FotoPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Materia", Storage="_Materia", ThisKey="ProfesorId", OtherKey="ProfesorId")]
		public EntitySet<Materia> Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				this._Materia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Materia(Materia entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = this;
		}
		
		private void detach_Materia(Materia entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = null;
		}
	}
}
#pragma warning restore 1591
